<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.lnyo-cly</groupId>
    <artifactId>ai4j-sdk</artifactId>

    <version>1.4.2</version>

    <packaging>pom</packaging>


    <modules>
        <module>ai4j</module>
        <module>ai4j-spring-boot-starter</module>
    </modules>
    <properties>
        <ai4j.version>0.0.1-SNAPSHOT</ai4j.version>
    </properties>

<!--    <build>-->
<!--        <defaultGoal>validate</defaultGoal>-->
<!--        <plugins>-->
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-deploy-plugin</artifactId>-->
<!--                <configuration>-->
<!--                    <skip>true</skip>-->
<!--                </configuration>-->
<!--            </plugin>-->
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-install-plugin</artifactId>-->
<!--                <configuration>-->
<!--                    <skip>true</skip>-->
<!--                </configuration>-->
<!--            </plugin>-->
<!--        </plugins>-->
<!--    </build>-->
    <!-- Source attach plugin -->
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <distributionManagement>
        <snapshotRepository>
            <id>snapshots</id>
            <url>http://m2.bigrule.com/artifactory/libs-snapshot-local</url>
        </snapshotRepository>
        <repository>
            <id>central</id>
            <url>http://m2.bigrule.com/artifactory/libs-release-local</url>
        </repository>
    </distributionManagement>




</project>